### ISSUE TITLE
Search form is hijacking the keyboard

### ISSUE THREAD

**Issue by RoneoOrg** [Lednerb/bilberry-hugo-theme#378]
Hi,

## The problem

Bilberry provides a search form, and using the keyboard triggers this form and steals the focus.

This is a problem for two reasons:
- keyboard users are annoyed (#a11y)
- search does not work out-of-the-box (as an Algolia token is required AFAIK) and this theme seems broken

## Proposal

Disable this form by default

I can submit a PR

**Comment by RoneoOrg** [comment]
Done, see https://github.com/RoneoOrg/bilberry-hugo-theme/pull/1

**Comment by igor-baiborodine** [comment]
The documentation on site configuration was updated to explicitly disable the Algolia Search functionality:
![image](https://user-images.githubusercontent.com/1027701/159527394-676ad5bf-dfc5-4618-b5c2-664e993c5dac.png)

**Comment by RoneoOrg** [comment]
Thanks Igor for considering this issue!

Still, even when Algolia is correctly set up, I would favor _as default_ a simple search form (i.e without automatic focus):
this behavior is super destabilizing for keyboard users. (Note that I don't have any dataset to support my point here 😅 -- hence closing this issue, I'll just tweak it on my side!)

Your write-up is crystal clear BTW, Thanks!

**Comment by igor-baiborodine** [comment]
This issue is still legit, it should not steal the focus. I'm re-opening this issue. I'll try to fix it.

**Comment by igor-baiborodine** [comment]
Fixed in PR https://github.com/Lednerb/bilberry-hugo-theme/pull/380.

**Comment by RoneoOrg** [comment]
> Fixed in PR #380.

Confirmed, thanks!
